---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-CleanupTask
no_index:
  directory:
    - t
    - inc
requires:
  Config::Simple: '0'
  Cwd: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Find: '0'
  File::Find::Rule: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Temp: '0'
  File::Touch: '0'
  File::Which: '0'
  Getopt::Long: '0'
  IPC::Run3: '0'
  Sort::Key: '0'
  Test::CheckManifest: '0'
  Test::File: '1.33'
  Test::More: '0'
  Test::Pod: '0'
  Test::Pod::Coverage: '0'
version: '0.11'
