---
abstract: 'Delete/Backup files on a task-based configuration'
author:
  - 'Savio Dimatteo <savio@lokku.com>'
build_requires:
  Config::Simple: 4.58
  Cwd: 3.29
  File::Basename: 2.76
  File::Find::Rule: 0.33
  File::Path: 2.07
  File::Spec: 3.29
  File::Temp: 0.2
  File::Touch: 0.08
  Test::CheckManifest: 0.9
  Test::File: 1.33
  Test::More: 0.98
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-CleanupTask
provides:
  File::CleanupTask:
    file: lib/File/CleanupTask.pm
    version: 0.03
requires:
  Config::Simple: 4.58
  File::Basename: 2.76
  File::Copy: 2.11
  File::Find: 1.12
  File::Path: 2.07
  File::Spec: 3.29
  File::Which: 1.09
  Getopt::Long: 2.37
  IPC::Run3: 0.045
  Sort::Key: 1.28
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
